### ISSUE TITLE
Transport endpoint not connected

### ISSUE THREAD

**Issue by jonesb63** [dweidenfeld/plexdrive#151]
I have used rclone a lot but for some reason I can't use this.

my mount string is ` ./plexdrive /var/lib/plex*/google -o allow_other`

the folder says"transport endpoint is not connected", I have already authed successfully, any ideas?

**Comment by rwenz3l** [comment]
try to unmount the folder with `fusermount -uz /path/to/mount`.. also multiple times in case there has been an accidental mount..

**Comment by jonesb63** [comment]
I tried that multiple times, I can mount with rclone just fine but everytime I try mounting with plexdrive I get transport endpoint not connected when trying to access mount folder.  I tried different folders and restarting and reinstalling

**Comment by rwenz3l** [comment]
Try to increase the verbosity. My Drive took 20mins to cache before i could use it..
Info shoud give you enough output to see what happens.
`plexdrive -o allow_other --verbosity=2 /mnt/google`

**Comment by zenjabba** [comment]
Please join us on the slack channel for one on one help

https://plexdrive.slack.com/shared_invite/MTg1NTg5NzY2Njc4LTE0OTUwNDU3NzAtMjJjNWRiMTAxMg

**Comment by MattTwinkleToes** [comment]
I have the same problem, Was there a solution to this that could be posted here?

**Comment by MattTwinkleToes** [comment]
I would like to but I don´t see any logs or entries in syslog that relate to fuse or plexdrive.  Can you help me out with a location for a log file?

I did upload about 700GB of content to google drive about 2 or 3 days ago but it I have barely used more than 50GB since then..  I have two servers, one server seems to be using plex drive happily enough and today i built a new server to use for testing.

It is this new server that I am having this problem with.

I have used both the same oauth credentials and a new set, same problem with both so i suppose it is not an api auth problem with google.

Not sure what else to tell you really

**Comment by yavg** [comment]
df -h
check which one is 100% clean it up, get some room.
then remount
fusermount -qzu /home/xxx
rclone mount xxx:xx /home/xxx
