### ISSUE TITLE
Run without mongoDB

### ISSUE THREAD

**Issue by jbreitbart** [dweidenfeld/plexdrive#168]
Is it possible run the latest release of plexdrive without mongoDB? MongoDB seems not to be available for 32bit Arm (e.g. Arm v7), but you provide a binary.

**Comment by zenjabba** [comment]
no, it needs mongodb. You can run it on another server and point the plexdrive app to use that other server for it's database.

**Comment by jbreitbart** [comment]
That seems really unpractical. I think I'll stick with the old release for the time being. Do you mind sharing on why you do not support both, the old internal mechanism and the new mongoDB one?

**Comment by zenjabba** [comment]
The old internal method had race conditions leading to lost files and was significantly slower. I'm sorry you think it's "unpractical", but a choice was made to move this way. The reason we allow "external" databases to be used is exactly this situation, so you can run plexdrive on small systems, but have an external database working correctly on a supported system.

**Comment by jbreitbart** [comment]
Thanks for the explanation. Performance was always good enough for me, but I understand that you don't want to include buggy code.

Would a pull-request with an additional cache-backend have a chance of being accepted? I am not sure if I find time to work on this, but I am wondering if it makes sense to try.

**Comment by Miladiir** [comment]
I think that it's important to point out that removing buggy code and replacing functionality with an external dependency is a really bad idea, especially when switching to MongoDB (the best nosql database available on planet earth \s)
I can understand this decision if it is just temporary, but it is no communicated this way unfortunately.

You really should consider internalizing whatever you are doing with the database. If its just cashing directory structure and file metadata + which parts are cached, then you really should be using sqlite instead of a full blown (and arguably bad) database server.
