### ISSUE TITLE
beta 4.1.0-beta-1498397749 plexdrive causes rclone mount to stop responding

### ISSUE THREAD

**Issue by 2600box** [dweidenfeld/plexdrive#201]
overnight rclone crypt mount on plexdrive died with tons of `File.Open failed: open for read: read /mnt/plexdrive/bucket` errors. 
the error debian gives in terminal is: `Transport endpoint is not connected`
unmounting and remounting works. 

in the plexdrive log there was just a lot of `Stopping playback of 0B-…` 

i am on beta 4.1.0-beta-1498397749 and use `plexdrive -v 2 /mnt/plexdrive` and `rclone mount --allow-other local-crypt: /mnt/media`

Looking through the log I can see some 403 errors with messages like this:
`WARNING: Could not read object ... / StatusCode: 403`

**Comment by ajkis** [comment]
Did you remount plexdrive as well.

**Comment by 2600box** [comment]
no, i left the plexdrive as is. despite its errors, it seems fine. broadly speaking the problem seems to be the instability of plexdrive/gdrive. rclone doesn't recover well from them, which is an rclone problem, but I'd really love plexdrive to be rock solid stable.

**Comment by ajkis** [comment]
rclone does not recover if plexdrive dropped and it was remounted by your service or script.
What you need to do is make sure that when plexdrive is being remounted that you remount your rclone mount as well. 

The easiest way to do it, is to add to your rclone mount script the part bellow and run it in cron tab every minute.  

```
if  [[ ! -f "/mnt/rclonemount/checkfile" ]]; then
fusermount -uz /mnt/rclonemount
sleep 1
rclone mount + all params
fi 

```
Make sure you create some checkfile that will be tested and basically if that file is not accessible rclone will unmount and remount. 

Do not use the test like `if mountpoint -q /mnt/rclonemount ; then` since that one can be seccesfull even when mount craps out, always test if file is accessible.
