### ISSUE TITLE
Cache calulation

### ISSUE THREAD

**Issue by JAC2703** [dweidenfeld/plexdrive#241]
Hi Guys,

Version 5.0.0 on linux.

I'm trying to understand how to calculate the max-chunks size.

I assumed it would be (chunk-size *  max-chunks), with a small provision for overhead but that doesn't seem to be the case. 

If I would like to consume 20GB of RAM, and have a chunk size of 6MB, how would I calculate the max-chunks value?

**Comment by dweidenfeld** [comment]
20gb = 20.000mb / 6mb = max-chunks

If it consumes more than 20gb this is due to the fact that the garbage collection did not started yet, so e.g. I've set mine to consume 5gb ram, but it will use up to 25gb ram because, my system has the amount of ram. As soon as my system needs the ram for other processes it drops down to ~5gb ram (as you already mentioned, there is a small overhead).
