### ISSUE TITLE
Disk-backed chunk storage

### ISSUE THREAD

**Issue by geoah** [dweidenfeld/plexdrive#242]
Is there a reason why chunk storage is only in-memory?
We're still in the process of checking out `plexdrive` but I can see the this being our main bottleneck.

The comments in `storage.go` seem to be hinting towards disk caching, but doesn't seem to be implemented right now. Could someone provide some more info on what the plan was?
eg:
> // Clear removes all old chunks on disk (will be called on each program start)

> // Store stores a chunk in the RAM and adds it to the disk storage queue

I haven't thoroughly checked out the code and all the edge cases, but unless there are big concerns or issues that I'm missing I'd be very interested in giving disk-caching a shot. Any suggestions/hints/ideas would be greatly appreciated.

**Comment by dweidenfeld** [comment]
Disk caching was implemented already, but with the multi-threaded solution it was not fast enough, so I wanted to add a RAM cache which async syncs to disk.
This is still the idea, but due to the lack of time I cannot implement it myself.

Also I've experimented with a rust version of plexdrive, because I think it could get a lot faster, but hey... I don't have the time to finish it right now.

All in all the project is stalled right now and I think I'll continue development in november/december (winter).

**Comment by geoah** [comment]
Hey, @dweidenfeld thanks for the quick response.
I wasn't trying to get you to implement this, I was just wondering what your plans were for this.

I've hacked together a simple version with disk caching, and I'll try to optimize it a bit and I'll probably add a hybrid (memory with async disk writes) solution as the one you described with different stack sizes for memory and disk.

First iteration of a simply disk cache implementation: https://github.com/geoah/plexdrive/commit/db87b3d32b9491d97672dedad13de82595583e1d

**Comment by dweidenfeld** [comment]
Nice.. Thank you for your support.
Please be aware of the following issues I had with disk caching:
- race conditions / synchronization issues
- performance decreases initially
- performance decreases over time
