### ISSUE TITLE
settings to consume less ram?

### ISSUE THREAD

**Issue by chienb** [dweidenfeld/plexdrive#246]
My library is ~10TB and my seedbox has 4GB (8GB virtual) ram. After mounting with the following settings, I hit ~15GB memory cached in like 20 mins:

```
-o allow_other \
--chunk-check-threads=10 \
--chunk-load-ahead=4 \
--chunk-load-threads=10 \
--chunk-size=5M \
--max-chunks=2000 \
--refresh-interval=1m \
```

What settings should I be using to lower ram usage while being able to stream remuxes? I have 1G fiber connection.

**Comment by dweidenfeld** [comment]
`--max-chunks`

the formula is like this:
`max-chunks * chunk-size =~ minimum amount of mb/gb in ram`

so for your settings you can calculate
`2000 * 5 = 5000`

so your program will use minimum 5gb in ram... 

my settings are 200 * 10 ... so just 1gb in ram... even 500mb should be more than enough for normal usage.

I cannot stop plexdrive from consuming more ram, because this is up to the gc of golang ;)

**Comment by snickers2k** [comment]
is this really the only option that matters?
i have it like this
```
ExecStart=/usr/local/bin/plexdrive mount \
  -c /root/.plexdrive \
  -o allow_other \
  --chunk-check-threads=10 \
  --chunk-load-ahead=6 \
  --chunk-load-threads=10 \
  --chunk-size=20M \
  --max-chunks=1500 \
  --umask=0777 \
```

and right now, its at around 42GB RAM .. but 1500*20 = 30GB .. :/ and i really don't want it to use more than that :)

oh and btw. what exactly is this a high ram-usage good for? i have not experienced much of a speed up. so is it obsolete if plexdrive uses more than for example 4GB ?

**Comment by kanenses** [comment]
Hello,
can help someone, this is my settings and run great:

>        -v 3 --refresh-interval=1m \
        --chunk-check-threads=4 \
        --chunk-load-threads=4 \
        --chunk-load-ahead=4 \
        --max-chunks=20 \
