### ISSUE TITLE
oauth Token in Cache?

### ISSUE THREAD

**Issue by xyber411** [dweidenfeld/plexdrive#36]
It would make things a bit easier regarding rebuilds / moves if the oath token was moved from the cache to the config file.  Then we could just delete the cache and have it rebuild in the case of a complete de-sync / corrupt db.

**Comment by dweidenfeld** [comment]
I've implemented this approach before but thought it is much nicer if there are only a few files in the .plexdrive folder. 
I will also have to store the LargestChangeID externally because it is also stored in the cache file.

I will think about it and maybe implement it again.

One last thing.... if you cache gets corrupted, you will have to do a full rebuild never the less. I cannot imagine, how storing the token externally will help you in this situation, because you will also have to reset the LargestChangeID ;)

**Comment by xyber411** [comment]
Storing the token externally solves the problem of automation.  Having to generate a new oauth is a manual process, which if it were just stored separately, then the cache could just regenerate during a normal scripted mount.

**Comment by dweidenfeld** [comment]
Okay, sound good. I will implement it later today.

**Comment by dweidenfeld** [comment]
Implemented for next release.
