### ISSUE TITLE
Slack link not working

### ISSUE THREAD

**Issue by lollilol** [dweidenfeld/plexdrive#438]
the link to the slack channel isn't working anymore
https://github.com/plexdrive/plexdrive#support

**Comment by dweidenfeld** [comment]
Hey, most people moved already to https://rclone.org/ since plexdrive was mostly a fill in replacement, because of some big missing features in rclone.

The Slack channel has been discontinued by Slack and probably won't come back again.

Also Google now starts to enforce the storage limits, which means probably also won't work anymore soon.
