### ISSUE TITLE
Question: slow single file read/copy speed

### ISSUE THREAD

**Issue by scoopydude2002** [dweidenfeld/plexdrive#51]
Hi, I've been testing plexdrive on my dedicated 1G server. I haven't use it with Plex yet but I did a speedtest using pv and was only able to get 4-5MB/s single file copy with plexdrive. Whereas with node-gdrive-fuse I can get 30MB/s single file copy. I'm not sure if this is intentional to reduce ban and the speed will be faster when actually using Plex? I'm using the default settings on version 1.2.0.

**Comment by dweidenfeld** [comment]
I never tested pv/cp because this project is just for playing media files, but I know that plex uses multiple threads for reading a media file. Every plex read request spawns a separate reading thread in the buffer.

Please test the setup with plex. I don't think you will see stuttering/buffering otherwise you should play with your settings.
