### ISSUE TITLE
Recommended chunk size

### ISSUE THREAD

**Issue by jaketame** [dweidenfeld/plexdrive#55]
I see the default chunk is 5MB, when working with an rclone buffer of 500MB. What would be the best chunk size

my average size of two libraries are as follows;

AVG MB= 2925.73
AVG MB= 2328.14

**Comment by dweidenfeld** [comment]
This varies depending on your network speed.

For me e.g. I have a 100mbit/s connection. 5MB seems to be perfect for me.

A lower chunk size helps you starting a movie more quickly but could make the movie buffering while it's playing. A bigger chunk size makes the initial load time slower.

If you have a 1gbit/s connection I think you can increase the chunk size to around 20mb, because you will have a much faster download speed, so the movie should start even quickly than with my 100mbit/s connection.
This is just an explanation... you have to find the best settings for your hardware/connection yourself ;)
