### ISSUE TITLE
Slice Bounds Out Of Range

### ISSUE THREAD

**Issue by lloydie2009** [dweidenfeld/plexdrive#73]
Hello, 

I'm seeing issues with plexdrive,  it all seems to work fine until I play something. I see the media files in the mount, however when I hit play plexdrive returns the below. 

I'm not running with any switches at all, simply ". /plexdrive /mnt/data" 

My library is about 15TB.

I rescan ed following my switch to plexdrive which completed fine but on the next play request, I see the same error. 

Any advice would be appreciated. 

PLEXDRIVE-LINUX-AMD64] [2017-05-14 20:33] DEBUG  : Requesting object 0B9FTkLZ5jUPAVmIwQ1JJWFhfWUE bytes 5242880 - 10485760 from API
panic: runtime error: slice bounds out of range

goroutine 82165 [running]:
main.(*Buffer).ReadBytes(0xc4214706c0, 0x500001, 0x1000, 0x180001, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:226 +0xc85
main.(*Buffer).ReadBytes.func2(0xc4214706c0, 0x500000, 0x1000)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:222 +0x4f
created by main.(*Buffer).ReadBytes
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:223 +0xce1

**Comment by animosity22** [comment]
What version are you running?

**Comment by Qwatuz** [comment]
Is this the same thing happening here?

`May 15 01:57:18 Mock5 plexdrive[22752]: 2017/05/15 01:57:18 fuse: panic in handler for Read [ID=0xb78 Node=0x2ec Uid=123 Gid=132 Pid=23932] 0x1 4096 @0x1000 dir=false fl=0 lock=0 ffl=OpenReadOnly: runtime error: slice bounds out of range
May 15 01:57:18 Mock5 plexdrive[22752]: goroutine 8052 [running]:
May 15 01:57:18 Mock5 plexdrive[22752]: bazil.org/fuse/fs.(*Server).serve.func2(0xda09e0, 0xc420192000, 0xc4204bbef8, 0xc4204bbe57)
May 15 01:57:18 Mock5 plexdrive[22752]:         /go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
May 15 01:57:18 Mock5 plexdrive[22752]: panic(0x8ff4c0, 0xd8df40)
May 15 01:57:18 Mock5 plexdrive[22752]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
May 15 01:57:18 Mock5 plexdrive[22752]: main.(*Buffer).ReadBytes(0xc4209f9000, 0x1000, 0x1000, 0x447100, 0x0, 0x0, 0x0, 0x0, 0x0)
May 15 01:57:18 Mock5 plexdrive[22752]:         /go/src/github.com/dweidenfeld/plexdrive/buffer.go:226 +0xc85
May 15 01:57:18 Mock5 plexdrive[22752]: main.(*Object).Read(0xc4209092f0, 0x7f689084e310, 0xc420844000, 0xc420192000, 0xc420bb4020, 0x1001, 0xc4209fc690)
May 15 01:57:18 Mock5 plexdrive[22752]:         /go/src/github.com/dweidenfeld/plexdrive/mount.go:240 +0x5a
May 15 01:57:18 Mock5 plexdrive[22752]: bazil.org/fuse/fs.(*Server).handleRequest(0xc4200ec0c0, 0x7f689084e310, 0xc420844000, 0xd9bde0, 0xc4209092f0, 0xc420bf8640, 0xda09e0, 0xc420192000, 0xc4204bbef8, 0xc420857ef8, ...)
May 15 01:57:18 Mock5 plexdrive[22752]:         /go/src/bazil.org/fuse/fs/serve.go:1249 +0x998
May 15 01:57:18 Mock5 plexdrive[22752]: bazil.org/fuse/fs.(*Server).serve(0xc4200ec0c0, 0xda09e0, 0xc420192000)
May 15 01:57:18 Mock5 plexdrive[22752]:         /go/src/bazil.org/fuse/fs/serve.go:878 +0x495
May 15 01:57:18 Mock5 plexdrive[22752]: bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200ec0c0, 0xda09e0, 0xc420192000)
May 15 01:57:18 Mock5 plexdrive[22752]:         /go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
May 15 01:57:18 Mock5 plexdrive[22752]: created by bazil.org/fuse/fs.(*Server).Serve
May 15 01:57:18 Mock5 plexdrive[22752]:         /go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
May 15 01:57:18 Mock5 plexdrive[22752]: panic: runtime error: slice bounds out of range
May 15 01:57:18 Mock5 plexdrive[22752]: goroutine 6890 [running]:
May 15 01:57:18 Mock5 plexdrive[22752]: main.(*Buffer).ReadBytes(0xc4209f9000, 0x500001, 0x1000, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
May 15 01:57:18 Mock5 plexdrive[22752]:         /go/src/github.com/dweidenfeld/plexdrive/buffer.go:226 +0xc85
May 15 01:57:18 Mock5 plexdrive[22752]: main.(*Buffer).ReadBytes.func2(0xc4209f9000, 0x500000, 0x1000)
May 15 01:57:18 Mock5 plexdrive[22752]:         /go/src/github.com/dweidenfeld/plexdrive/buffer.go:222 +0x4f
May 15 01:57:18 Mock5 plexdrive[22752]: created by main.(*Buffer).ReadBytes
May 15 01:57:18 Mock5 plexdrive[22752]:         /go/src/github.com/dweidenfeld/plexdrive/buffer.go:223 +0xce1
May 15 01:57:18 Mock5 systemd[1]: plexram.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 15 01:57:18 Mock5 systemd[1]: plexram.service: Unit entered failed state.
May 15 01:57:18 Mock5 systemd[1]: plexram.service: Failed with result 'exit-code'.
`

Happens when I am doing a Plex library update. It was working fine all day (using latest 2.1.1 version) until now.

I am running it in RAM if that makes a difference.

Here is a log level 3 of it happening:


`[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting children for 0B3f2GDLu6W5MaDJ3ZHZGeXZYeFk
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] WARNING: Could not find children for parent 0B3f2GDLu6W5MaDJ3ZHZGeXZYe                                                                                                                          Fk in cache
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting children for 0B3f2GDLu6W5MTUM1NnYxRVJFSWc
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting children for 0B3f2GDLu6W5Md0Q4dTVFMmtCVFU
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting object The.Magnificent.Seven.2016.BluRay.1080p.DTS-HD                                                                                                                          .MA.7.1.AVC.REMUX-FraMeSToR.nfo in parent 0B3f2GDLu6W5Md0Q4dTVFMmtCVFU
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting children for 0B3f2GDLu6W5MTUM1NnYxRVJFSWc
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting children for 0B3f2GDLu6W5MSmoyVW84d1RkUHM
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] WARNING: Could not find children for parent 0B3f2GDLu6W5MSmoyVW84d1RkU                                                                                                                          HM in cache
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting children for 0B3f2GDLu6W5MTUM1NnYxRVJFSWc
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting children for 0B3f2GDLu6W5MNld2Ty1JRm5GUEU
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting object tns.nfo in parent 0B3f2GDLu6W5MNld2Ty1JRm5GUEU
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting object The.NeverEnding.Story.1984.1080p.Blu-ray.VC-1.                                                                                                                          DTS-HD.MA.5.1.REMUX-FraMeSToR.mkv in parent 0B3f2GDLu6W5MNld2Ty1JRm5GUEU
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting children for 0B3f2GDLu6W5MTUM1NnYxRVJFSWc
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting children for 0B3f2GDLu6W5MTUM1NnYxRVJFSWc
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting children for 0B3f2GDLu6W5MNld2Ty1JRm5GUEU
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] INFO   : Starting playback of tns.nfo
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Creating buffer for object 0B3f2GDLu6W5MNGJJMlRGRjU2X0E
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting object 0B3f2GDLu6W5MNGJJMlRGRjU2X0E - chunk 0 - offse                                                                                                                          t 0 for 4096 bytes (is preload: false)
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Requesting object 0B3f2GDLu6W5MNGJJMlRGRjU2X0E bytes 0 - 5242                                                                                                                          880 from API
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting object 0B3f2GDLu6W5MNGJJMlRGRjU2X0E - chunk 0 - offse                                                                                                                          t 4096 for 4096 bytes (is preload: false)
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Found file /tmp/chunks/0B3f2GDLu6W5MNGJJMlRGRjU2X0E/0 bytes 0                                                                                                                           - 5242880 in cache
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] INFO   : Stopping playback of tns.nfo
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Stop buffering for object 0B3f2GDLu6W5MNGJJMlRGRjU2X0E
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] INFO   : Starting playback of The.NeverEnding.Story.1984.1080p.Blu-ray                                                                                                                          .VC-1.DTS-HD.MA.5.1.REMUX-FraMeSToR.mkv
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Creating buffer for object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ - chunk 0 - offse                                                                                                                          t 0 for 4096 bytes (is preload: false)
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Requesting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ bytes 0 - 5242                                                                                                                          880 from API
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ - chunk 5242880 -                                                                                                                           offset 1 for 4096 bytes (is preload: true)
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Requesting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ bytes 5242880                                                                                                                           - 10485760 from API
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ - chunk 0 - offse                                                                                                                          t 4096 for 4096 bytes (is preload: false)
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : <nil>
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Could not read file /tmp/chunks/0B3f2GDLu6W5MUWMxTG1vT0VkRjQ/                                                                                                                          0 at 4096
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Requesting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ bytes 0 - 5242                                                                                                                          880 from API
2017/05/15 02:00:52 fuse: panic in handler for Read [ID=0x1f0 Node=0xac Uid=123 Gid=132 Pid=26513] 0x1 4096 @0x1000                                                                                                                           dir=false fl=0 lock=0 ffl=OpenReadOnly: runtime error: slice bounds out of range
goroutine 10493 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0xda09e0, 0xc4201591f0, 0xc420a6def8, 0xc420a6de57)
        /go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x8ff4c0, 0xd8df40)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
main.(*Buffer).ReadBytes(0xc42069ab00, 0x1000, 0x1000, 0x447100, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:226 +0xc85
main.(*Object).Read(0xc4207b4f00, 0x7f7ba4ba69f8, 0xc42064f680, 0xc4201591f0, 0xc420622b40, 0x1001, 0xc420ea3a78)
        /go/src/github.com/dweidenfeld/plexdrive/mount.go:240 +0x5a
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200db140, 0x7f7ba4ba69f8, 0xc42064f680, 0xd9bde0, 0xc4207b4f00, 0xc42                                                                                                                          0445b40, 0xda09e0, 0xc4201591f0, 0xc420a6def8, 0xc420727b60, ...)
        /go/src/bazil.org/fuse/fs/serve.go:1249 +0x998
bazil.org/fuse/fs.(*Server).serve(0xc4200db140, 0xda09e0, 0xc4201591f0)
        /go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200db140, 0xda09e0, 0xc4201591f0)
        /go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
        /go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ - chunk 5242880 -                                                                                                                           offset 1 for 4096 bytes (is preload: true)
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Requesting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ bytes 5242880                                                                                                                           - 10485760 from API
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Getting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ - chunk 178887065                                                                                                                          60 - offset 4386816 for 4096 bytes (is preload: false)
[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Requesting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ bytes 17888706                                                                                                                          560 - 17893949440 from API
panic: runtime error: slice bounds out of range

goroutine 10414 [running]:
main.(*Buffer).ReadBytes(0xc42069ab00, 0x500001, 0x1000, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:226 +0xc85
main.(*Buffer).ReadBytes.func2(0xc42069ab00, 0x500000, 0x1000)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:222 +0x4f
created by main.(*Buffer).ReadBytes
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:223 +0xce1
ls: cannot access 'plexdrive': Transport endpoint is not connected
`

**Comment by lloydie2009** [comment]
Version 2.1.1 here too. Should we try previous versions?

**Comment by dweidenfeld** [comment]
Bugfix included in next version.

**Comment by lloydie2009** [comment]
For anyone interested, until the next version is released, using 2.1.0 works great. 

--------------------------------------------
On Mon, 15/5/17, Qwatuz <notifications@github.com> wrote:

 Subject: Re: [dweidenfeld/plexdrive] Slice Bounds Out Of Range (#73)
 To: "dweidenfeld/plexdrive" <plexdrive@noreply.github.com>
 Cc: "lloydie2009" <lloydie2009@googlemail.com>, "Author" <author@noreply.github.com>
 Date: Monday, 15 May, 2017, 3:11
 
 Is this the same thing happening
 here?
 May 15 01:57:18 Mock5 plexdrive[22752]: 2017/05/15
 01:57:18 fuse: panic in handler for Read [ID=0xb78
 Node=0x2ec Uid=123 Gid=132 Pid=23932] 0x1 4096 @0x1000
 dir=false fl=0 lock=0 ffl=OpenReadOnly: runtime error: slice
 bounds out of range May 15 01:57:18 Mock5 plexdrive[22752]:
 goroutine 8052 [running]: May 15 01:57:18 Mock5
 plexdrive[22752]:
 bazil.org/fuse/fs.(*Server).serve.func2(0xda09e0,
 0xc420192000, 0xc4204bbef8, 0xc4204bbe57) May 15 01:57:18
 Mock5 plexdrive[22752]:
 /go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1 May 15
 01:57:18 Mock5 plexdrive[22752]: panic(0x8ff4c0, 0xd8df40)
 May 15 01:57:18 Mock5 plexdrive[22752]:
 /usr/local/go/src/runtime/panic.go:489 +0x2cf May 15
 01:57:18 Mock5 plexdrive[22752]:
 main.(*Buffer).ReadBytes(0xc4209f9000, 0x1000, 0x1000,
 0x447100, 0x0, 0x0, 0x0, 0x0, 0x0) May 15 01:57:18 Mock5
 plexdrive[22752]:
 /go/src/github.com/dweidenfeld/plexdrive/buffer.go:226
 +0xc85 May 15 01:57:18 Mock5 plexdrive[22752]:
 main.(*Object).Read(0xc4209092f0, 0x7f689084e310,
 0xc420844000, 0xc420192000, 0xc420bb4020, 0x1001,
 0xc4209fc690) May 15 01:57:18 Mock5 plexdrive[22752]:
 /go/src/github.com/dweidenfeld/plexdrive/mount.go:240 +0x5a
 May 15 01:57:18 Mock5 plexdrive[22752]:
 bazil.org/fuse/fs.(*Server).handleRequest(0xc4200ec0c0,
 0x7f689084e310, 0xc420844000, 0xd9bde0, 0xc4209092f0,
 0xc420bf8640, 0xda09e0, 0xc420192000, 0xc4204bbef8,
 0xc420857ef8, ...) May 15 01:57:18 Mock5 plexdrive[22752]:
 /go/src/bazil.org/fuse/fs/serve.go:1249 +0x998 May 15
 01:57:18 Mock5 plexdrive[22752]:
 bazil.org/fuse/fs.(*Server).serve(0xc4200ec0c0, 0xda09e0,
 0xc420192000) May 15 01:57:18 Mock5 plexdrive[22752]:
 /go/src/bazil.org/fuse/fs/serve.go:878 +0x495 May 15
 01:57:18 Mock5 plexdrive[22752]:
 bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200ec0c0,
 0xda09e0, 0xc420192000) May 15 01:57:18 Mock5
 plexdrive[22752]: /go/src/bazil.org/fuse/fs/serve.go:425
 +0x6e May 15 01:57:18 Mock5 plexdrive[22752]: created by
 bazil.org/fuse/fs.(*Server).Serve May 15 01:57:18 Mock5
 plexdrive[22752]: /go/src/bazil.org/fuse/fs/serve.go:426
 +0x3c4 May 15 01:57:18 Mock5 plexdrive[22752]: panic:
 runtime error: slice bounds out of range May 15 01:57:18
 Mock5 plexdrive[22752]: goroutine 6890 [running]: May 15
 01:57:18 Mock5 plexdrive[22752]:
 main.(*Buffer).ReadBytes(0xc4209f9000, 0x500001, 0x1000,
 0x1, 0x0, 0x0, 0x0, 0x0, 0x0) May 15 01:57:18 Mock5
 plexdrive[22752]:
 /go/src/github.com/dweidenfeld/plexdrive/buffer.go:226
 +0xc85 May 15 01:57:18 Mock5 plexdrive[22752]:
 main.(*Buffer).ReadBytes.func2(0xc4209f9000, 0x500000,
 0x1000) May 15 01:57:18 Mock5 plexdrive[22752]:
 /go/src/github.com/dweidenfeld/plexdrive/buffer.go:222 +0x4f
 May 15 01:57:18 Mock5 plexdrive[22752]: created by
 main.(*Buffer).ReadBytes May 15 01:57:18 Mock5
 plexdrive[22752]:
 /go/src/github.com/dweidenfeld/plexdrive/buffer.go:223
 +0xce1 May 15 01:57:18 Mock5 systemd[1]: plexram.service:
 Main process exited, code=exited, status=2/INVALIDARGUMENT
 May 15 01:57:18 Mock5 systemd[1]: plexram.service: Unit
 entered failed state. May 15 01:57:18 Mock5 systemd[1]:
 plexram.service: Failed with result
 'exit-code'.
 Happens when I am doing a Plex library update. It was
 working fine all day (using latest 2.1.1 version) until
 now.
 I am running it in RAM if that makes a difference.
 Here is a log level 3 of it happening:
 `[USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting children for 0B3f2GDLu6W5MaDJ3ZHZGeXZYeFk
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] WARNING: Could
 not find children for parent 0B3f2GDLu6W5MaDJ3ZHZGeXZYe     
                                                             
                                                        Fk in
 cache
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting children for 0B3f2GDLu6W5MTUM1NnYxRVJFSWc
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting children for 0B3f2GDLu6W5Md0Q4dTVFMmtCVFU
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting object
 The.Magnificent.Seven.2016.BluRay.1080p.DTS-HD              
                                                             
                                              
 .MA.7.1.AVC.REMUX-FraMeSToR.nfo in parent
 0B3f2GDLu6W5Md0Q4dTVFMmtCVFU
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting children for 0B3f2GDLu6W5MTUM1NnYxRVJFSWc
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting children for 0B3f2GDLu6W5MSmoyVW84d1RkUHM
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] WARNING: Could
 not find children for parent 0B3f2GDLu6W5MSmoyVW84d1RkU     
                                                             
                                                        HM in
 cache
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting children for 0B3f2GDLu6W5MTUM1NnYxRVJFSWc
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting children for 0B3f2GDLu6W5MNld2Ty1JRm5GUEU
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting object tns.nfo in parent
 0B3f2GDLu6W5MNld2Ty1JRm5GUEU
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting object
 The.NeverEnding.Story.1984.1080p.Blu-ray.VC-1.              
                                                             
                                              
 DTS-HD.MA.5.1.REMUX-FraMeSToR.mkv in parent
 0B3f2GDLu6W5MNld2Ty1JRm5GUEU
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting children for 0B3f2GDLu6W5MTUM1NnYxRVJFSWc
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting children for 0B3f2GDLu6W5MTUM1NnYxRVJFSWc
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting children for 0B3f2GDLu6W5MNld2Ty1JRm5GUEU
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] INFO   :
 Starting playback of tns.nfo
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Creating buffer for object 0B3f2GDLu6W5MNGJJMlRGRjU2X0E
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting object 0B3f2GDLu6W5MNGJJMlRGRjU2X0E - chunk 0 -
 offse                                                       
                                                             
      t 0 for 4096 bytes (is preload: false)
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Requesting object 0B3f2GDLu6W5MNGJJMlRGRjU2X0E bytes 0 -
 5242                                                        
                                                             
     880 from API
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting object 0B3f2GDLu6W5MNGJJMlRGRjU2X0E - chunk 0 -
 offse                                                       
                                                             
      t 4096 for 4096 bytes (is preload: false)
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Found
 file /tmp/chunks/0B3f2GDLu6W5MNGJJMlRGRjU2X0E/0 bytes 0     
                                                             
                                                         -
 5242880 in cache
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] INFO   :
 Stopping playback of tns.nfo
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Stop
 buffering for object 0B3f2GDLu6W5MNGJJMlRGRjU2X0E
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] INFO   :
 Starting playback of
 The.NeverEnding.Story.1984.1080p.Blu-ray                    
                                                             
                                        
 .VC-1.DTS-HD.MA.5.1.REMUX-FraMeSToR.mkv
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Creating buffer for object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ - chunk 0 -
 offse                                                       
                                                             
      t 0 for 4096 bytes (is preload: false)
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Requesting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ bytes 0 -
 5242                                                        
                                                             
     880 from API
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ - chunk 5242880
 -                                                           
                                                             
   offset 1 for 4096 bytes (is preload: true)
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Requesting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ bytes 5242880
                                                             
                                                             
 - 10485760 from API
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ - chunk 0 -
 offse                                                       
                                                             
      t 4096 for 4096 bytes (is preload: false)
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : 
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  : Could
 not read file /tmp/chunks/0B3f2GDLu6W5MUWMxTG1vT0VkRjQ/     
                                                             
                                                        0 at
 4096
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Requesting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ bytes 0 -
 5242                                                        
                                                             
     880 from API
 
 2017/05/15 02:00:52 fuse: panic in handler for Read
 [ID=0x1f0 Node=0xac Uid=123 Gid=132 Pid=26513] 0x1 4096 @0x1000               
                                                             
                                               dir=false fl=0
 lock=0 ffl=OpenReadOnly: runtime error: slice bounds out of
 range
 
 goroutine 10493 [running]:
 
 bazil.org/fuse/fs.(*Server).serve.func2(0xda09e0,
 0xc4201591f0, 0xc420a6def8, 0xc420a6de57)
 
 /go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
 
 panic(0x8ff4c0, 0xd8df40)
 
 /usr/local/go/src/runtime/panic.go:489 +0x2cf
 
 main.(*Buffer).ReadBytes(0xc42069ab00, 0x1000, 0x1000,
 0x447100, 0x0, 0x0, 0x0, 0x0, 0x0)
 
 /go/src/github.com/dweidenfeld/plexdrive/buffer.go:226
 +0xc85
 
 main.(*Object).Read(0xc4207b4f00, 0x7f7ba4ba69f8,
 0xc42064f680, 0xc4201591f0, 0xc420622b40, 0x1001,
 0xc420ea3a78)
 
 /go/src/github.com/dweidenfeld/plexdrive/mount.go:240 +0x5a
 
 bazil.org/fuse/fs.(*Server).handleRequest(0xc4200db140,
 0x7f7ba4ba69f8, 0xc42064f680, 0xd9bde0, 0xc4207b4f00, 0xc42 
                                                             
                                                           
 0445b40, 0xda09e0, 0xc4201591f0, 0xc420a6def8, 0xc420727b60,
 ...)
 
 /go/src/bazil.org/fuse/fs/serve.go:1249 +0x998
 
 bazil.org/fuse/fs.(*Server).serve(0xc4200db140, 0xda09e0,
 0xc4201591f0)
 
 /go/src/bazil.org/fuse/fs/serve.go:878 +0x495
 
 bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200db140,
 0xda09e0, 0xc4201591f0)
 
 /go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
 
 created by bazil.org/fuse/fs.(*Server).Serve
 
 /go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ - chunk 5242880
 -                                                           
                                                             
   offset 1 for 4096 bytes (is preload: true)
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Requesting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ bytes 5242880
                                                             
                                                             
 - 10485760 from API
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Getting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ - chunk
 178887065                                                   
                                                             
          60 - offset 4386816 for 4096 bytes (is preload:
 false)
 
 [USR/LOCAL/BIN/PLEXDRIVE] [2017-05-15 02:00] DEBUG  :
 Requesting object 0B3f2GDLu6W5MUWMxTG1vT0VkRjQ bytes
 17888706                                                    
                                                             
         560 - 17893949440 from API
 
 panic: runtime error: slice bounds out of range
 goroutine 10414 [running]:
 
 main.(*Buffer).ReadBytes(0xc42069ab00, 0x500001, 0x1000,
 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
 
 /go/src/github.com/dweidenfeld/plexdrive/buffer.go:226
 +0xc85
 
 main.(*Buffer).ReadBytes.func2(0xc42069ab00, 0x500000,
 0x1000)
 
 /go/src/github.com/dweidenfeld/plexdrive/buffer.go:222
 +0x4f
 
 created by main.(*Buffer).ReadBytes
 
 /go/src/github.com/dweidenfeld/plexdrive/buffer.go:223
 +0xce1
 
 ls: cannot access 'plexdrive': Transport endpoint is
 not connected
 
 `
 
 —
 You are
 receiving this because you authored the thread.
 Reply
 to this email directly, view
 it on GitHub, or mute
 the thread.
