### ISSUE TITLE
[HELP WANTED] Someone who want to write a rclone-crypt / plexdrive tutorial

### ISSUE THREAD

**Issue by dweidenfeld** [dweidenfeld/plexdrive#86]
Hey there,

can someone out there write a short noobish tutorial how to setup plexdrive with rclone crypt (with or without unionfs) and send it to me?
I would really appreciate that, because I currently do not have the time to fix the bugs/add features and write such a tutorial (and have some free time with my girlfriend ;) ).

Thank you :+1:

**Comment by spencercharest** [comment]
Hey @dweidenfeld I wrote this quick guide to decrypt an rclone encrypted Google Drive. I think I will write a very comprehensive step by step on setting up rclone, plexdrive, and unionfs from scratch on Linux. I'm just wondering if you think that guide would be worth it considering plexdrive may be incorporating crypt soon and rclone may not be needed. I am happy to help with this since I'd like to contribute to this project but I don't know Go so please don't hesitate to let me know if you would like anything clarified, fixed or any additional material written!

[instructions.md.zip](https://github.com/dweidenfeld/plexdrive/files/1008498/instructions.md.zip)

**Comment by Em31Et** [comment]
@spencercharest 
Maybe make it more simple, just step by step for edit the **.rclone.conf** via text editor?
Since plexdrive currently do not support WRITE, people absolutely already have **rclone crypt** setting.

**Comment by spencercharest** [comment]
@Em31Et right, that was my thinking. People will still need the rclone encrypted Google Drive remote to upload encrypted content. So instead of editing that remote the guide creates a new remote for decrypting content locally. Maybe I am misunderstanding you.

**Comment by Massaguana** [comment]
i use this 2 guides: https://github.com/dweidenfeld/plexdrive/issues/70 and https://github.com/hthighway/scripts/tree/master/plexdrive

The Step plexdrive.service now works, caching runs.. but i get still banned when i make an full library scan.

the step plexunion.service don´t work in the moment, i think there is something wrong with my unininfs.sh file

**Comment by dweidenfeld** [comment]
Thank you all. I will have a look on the tutorials and maybe we can use one of them as an installation guide.

@spencercharest I don't think that the crypt function will be implemented that soon. It is very complicated and there have been many new bug issues, that have to be fixed first.

**Comment by dweidenfeld** [comment]
I added a tutorial for mounting an encrypted rclone mount with plexdrive.
Feel free to add stuff to it and open PRs ;)
