### ISSUE TITLE
Thumbnail Generation

### ISSUE THREAD

**Issue by dabigc** [dweidenfeld/plexdrive#87]
Before I go get my Google account banned I'm wondering if anyone has used the thumbnail generation options in Plex with plexdrive? Those options are under the Settings->Server->Library

"Generate video preview thumbnails" and "Generate chapter thumbnails"

My understanding is Plex has to run through the video in order to generate the index files that contain these thumbnails. Is anyone using these with plexdrive on the backend? I don't want to break my setup for this one thing but I really like having these for my library. Thanks for the help!

**Comment by dany20mh** [comment]
Honestly I never use that, but I read other places that put too much pressure on the files and it has to read single one them over and over to get the thumbnails. 

So I would suggest don’t use it.

**Comment by animosity22** [comment]
Generate thumbnails will download your entire library one by one to process the whole file. It'll be a very time consuming process. I would "guess" it will not cause an API issue, but it will cause a lot of data to be downloaded. I have it turned off.

**Comment by dweidenfeld** [comment]
This could definitely cause an API issue, because in the Google API every new file request will count as request. So...
If you download one file chunk by chunk = 1 request
If you download 10.000 media files = 10.000 requests

I would expect, that plex downloads the files simultaneously so there are many more requests and you will exceed the quota limits.

Turn the option off and you should not get banned.
